### ISSUE TITLE
Allow adding new users to existing schedule.

### ISSUE THREAD

**Issue by subdavis** [WritingCenterScheduler/application#11]
For a given schedule, must be able to put users that were not part of the original schedule generation into the generated schedu.e

**Comment by subdavis** [comment]
Done by @rychco

**Comment by ghost** [comment]
Reopening issue because I think what Jackie meant was that she wants to be able to RUN the scheduler again from an existing configuration (such as in the case where she likes the schedule but hires another employee after the fact)

**Comment by subdavis** [comment]
Can we not?  This just isn't worth the time.
