### ISSUE TITLE
Font-Awesome Icons appear differently at different zoom levels

### ISSUE THREAD

**Issue by ghost** [WritingCenterScheduler/application#45]
At 100% the icons look good.
At anything other than 100% (on Chrome) and they look bad.

(Potentially a WONTFIX)

**Comment by subdavis** [comment]
@rychco I'm using chrome (Linux) and things look fine @ 250%

![screen](https://i.imgur.com/dvmqhL9l.png)

**Comment by ghost** [comment]
Not even gonna try to fix this
WONTFIX
