### ISSUE TITLE
Hours Per Week

### ISSUE THREAD

**Issue by subdavis** [WritingCenterScheduler/application#7]
Allow students to set their desired hours per week on the user availability page.

**Comment by subdavis** [comment]
Range would be ideal, but max would do

**Comment by subdavis** [comment]
@rychco we should talk about how to make the engine respect this preference?

**Comment by subdavis** [comment]
Added editable colors per week.  @rychco - how do we add to schedule?

@suBDavis we will add to schedule in one of two ways, either have a decrementing maximum hours attribute for each user (which can also be changed on an individual basis, this could be more flexible for Jackie), or simple remove hours beyond the maximum in post processing

**Comment by ghost** [comment]
What do you mean by editable colors per week?

**Comment by ghost** [comment]
Nevermind I see what you mean.

I am going to implement the desired hours component of scheduling into post processing. I will comment on that issue as well.
